#!/bin/bash

START=$(date +%s.%N)

while read i ; do
	cd build/classes/
	java -cp "/home/elvis/.m2/repository/com/mageddo/utils/0.1.8/utils-0.1.8.jar:." "$1.Main"<<< $i
done<'./in'

END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)
echo ""
echo "Rodou em $DIFF"
